/* tslint:disable */
/* eslint-disable */
/**
 * 接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 67890211@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Abc
 */
export interface Abc {
    /**
     * 开卡日
     * @type {string}
     * @memberof Abc
     */
    dueDay: string;
    /**
     * 进件渠道
     * @type {string}
     * @memberof Abc
     */
    requestChannel: string;
}

export function AbcFromJSON(json: any): Abc {
    return AbcFromJSONTyped(json, false);
}

export function AbcFromJSONTyped(json: any, ignoreDiscriminator: boolean): Abc {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dueDay': json['dueDay'],
        'requestChannel': json['requestChannel'],
    };
}

export function AbcToJSON(value?: Abc | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dueDay': value.dueDay,
        'requestChannel': value.requestChannel,
    };
}

