/* tslint:disable */
/* eslint-disable */
/**
 * 接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 67890211@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 带数据的返回数据
 * @export
 * @interface DataTransOutput
 */
export interface DataTransOutput {
    /**
     * 返回数据
     * @type {object}
     * @memberof DataTransOutput
     */
    data?: object;
    /**
     * 错误码。
     * 100000 成功
     * 200000 入参不合法
     * 400000 权限不足
     * 500000 服务失败
     * @type {number}
     * @memberof DataTransOutput
     */
    transCode: number;
    /**
     * 错误信息。成功：“成功” 失败：“失败对应的msg”
     * @type {string}
     * @memberof DataTransOutput
     */
    transMessage: string;
    /**
     * 信息详情”
     * @type {string}
     * @memberof DataTransOutput
     */
    transMessageDetail: string;
}

export function DataTransOutputFromJSON(json: any): DataTransOutput {
    return DataTransOutputFromJSONTyped(json, false);
}

export function DataTransOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataTransOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
        'transCode': json['transCode'],
        'transMessage': json['transMessage'],
        'transMessageDetail': json['transMessageDetail'],
    };
}

export function DataTransOutputToJSON(value?: DataTransOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'transCode': value.transCode,
        'transMessage': value.transMessage,
        'transMessageDetail': value.transMessageDetail,
    };
}

