/* tslint:disable */
/* eslint-disable */
/**
 * 接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 67890211@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Vo,
    VoFromJSON,
    VoFromJSONTyped,
    VoToJSON,
} from './';

/**
 * 
 * @export
 * @interface Tokenvo
 */
export interface Tokenvo {
    /**
     * 
     * @type {Vo}
     * @memberof Tokenvo
     */
    bizParamVo?: Vo;
}

export function TokenvoFromJSON(json: any): Tokenvo {
    return TokenvoFromJSONTyped(json, false);
}

export function TokenvoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tokenvo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bizParamVo': !exists(json, 'bizParamVo') ? undefined : VoFromJSON(json['bizParamVo']),
    };
}

export function TokenvoToJSON(value?: Tokenvo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bizParamVo': VoToJSON(value.bizParamVo),
    };
}

