/* tslint:disable */
/* eslint-disable */
/**
 * 接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 67890211@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DataTransOutput,
    DataTransOutputFromJSON,
    DataTransOutputFromJSONTyped,
    DataTransOutputToJSON,
} from './';

/**
 * 
 * @export
 * @interface 
 */
export interface  {
    /**
     * 开卡日
     * @type {string}
     * @memberof 
     */
    dueDay: string;
    /**
     * 进件渠道
     * @type {string}
     * @memberof 
     */
    requestChannel: string;
    /**
     * 
     * @type {{ [key: string]: DataTransOutput; }}
     * @memberof 
     */
    data?: { [key: string]: DataTransOutput; };
}

export function FromJSON(json: any):  {
    return FromJSONTyped(json, false);
}

export function FromJSONTyped(json: any, ignoreDiscriminator: boolean):  {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dueDay': json['dueDay'],
        'requestChannel': json['requestChannel'],
        'data': !exists(json, 'data') ? undefined : (mapValues(json['data'], DataTransOutputFromJSON)),
    };
}

export function ToJSON(value?:  | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dueDay': value.dueDay,
        'requestChannel': value.requestChannel,
        'data': value.data === undefined ? undefined : (mapValues(value.data, DataTransOutputToJSON)),
    };
}

