/* tslint:disable */
/* eslint-disable */
/**
 * 接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 67890211@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResultListMap
 */
export interface ResultListMap {
    /**
     * 
     * @type {string}
     * @memberof ResultListMap
     */
    description?: string;
}

export function ResultListMapFromJSON(json: any): ResultListMap {
    return ResultListMapFromJSONTyped(json, false);
}

export function ResultListMapFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultListMap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function ResultListMapToJSON(value?: ResultListMap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
    };
}

