/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ReplyVO,
    ReplyVOFromJSON,
    ReplyVOToJSON,
} from '../models';

export interface SaveUsingPOSTRequest {
    body?: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * 新增
     */
    async saveUsingPOSTRaw(requestParameters: SaveUsingPOSTRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReplyVO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/datamap/fieldDef`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReplyVOFromJSON(jsonValue));
    }

    /**
     * 新增
     */
    async saveUsingPOST(requestParameters: SaveUsingPOSTRequest, initOverrides?: RequestInit): Promise<ReplyVO> {
        const response = await this.saveUsingPOSTRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
