/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ListVO,
    ListVOFromJSON,
    ListVOFromJSONTyped,
    ListVOToJSON,
} from './';

/**
 * 
 * @export
 * @interface PageVOListVO
 */
export interface PageVOListVO {
    /**
     * 数据列表
     * @type {Array<ListVO>}
     * @memberof PageVOListVO
     */
    entities: Array<ListVO>;
    /**
     * 总条数
     * @type {number}
     * @memberof PageVOListVO
     */
    entityCount: number;
    /**
     * 开始序号
     * @type {number}
     * @memberof PageVOListVO
     */
    firstEntityIndex: number;
    /**
     * 结束序号
     * @type {number}
     * @memberof PageVOListVO
     */
    lastEntityIndex: number;
    /**
     * 总页数
     * @type {number}
     * @memberof PageVOListVO
     */
    pageCount: number;
    /**
     * 页码
     * @type {number}
     * @memberof PageVOListVO
     */
    pageNo: number;
    /**
     * 每页条数
     * @type {number}
     * @memberof PageVOListVO
     */
    pageSize: number;
}

export function PageVOListVOFromJSON(json: any): PageVOListVO {
    return PageVOListVOFromJSONTyped(json, false);
}

export function PageVOListVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageVOListVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entities': ((json['entities'] as Array<any>).map(ListVOFromJSON)),
        'entityCount': json['entityCount'],
        'firstEntityIndex': json['firstEntityIndex'],
        'lastEntityIndex': json['lastEntityIndex'],
        'pageCount': json['pageCount'],
        'pageNo': json['pageNo'],
        'pageSize': json['pageSize'],
    };
}

export function PageVOListVOToJSON(value?: PageVOListVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entities': ((value.entities as Array<any>).map(ListVOToJSON)),
        'entityCount': value.entityCount,
        'firstEntityIndex': value.firstEntityIndex,
        'lastEntityIndex': value.lastEntityIndex,
        'pageCount': value.pageCount,
        'pageNo': value.pageNo,
        'pageSize': value.pageSize,
    };
}

