/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PageVOFollowRecordVO,
    PageVOFollowRecordVOFromJSON,
    PageVOFollowRecordVOFromJSONTyped,
    PageVOFollowRecordVOToJSON,
} from './';

/**
 * 
 * @export
 * @interface ReplyVOPageVOFollowRecordVO
 */
export interface ReplyVOPageVOFollowRecordVO {
    /**
     * 响应代码【0正确,非0错误】
     * @type {string}
     * @memberof ReplyVOPageVOFollowRecordVO
     */
    code: string;
    /**
     * 
     * @type {PageVOFollowRecordVO}
     * @memberof ReplyVOPageVOFollowRecordVO
     */
    data?: PageVOFollowRecordVO;
    /**
     * 结果描述
     * @type {string}
     * @memberof ReplyVOPageVOFollowRecordVO
     */
    message: string;
}

export function ReplyVOPageVOFollowRecordVOFromJSON(json: any): ReplyVOPageVOFollowRecordVO {
    return ReplyVOPageVOFollowRecordVOFromJSONTyped(json, false);
}

export function ReplyVOPageVOFollowRecordVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplyVOPageVOFollowRecordVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'data': !exists(json, 'data') ? undefined : PageVOFollowRecordVOFromJSON(json['data']),
        'message': json['message'],
    };
}

export function ReplyVOPageVOFollowRecordVOToJSON(value?: ReplyVOPageVOFollowRecordVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'data': PageVOFollowRecordVOToJSON(value.data),
        'message': value.message,
    };
}

