/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ReplyVOint,
    ReplyVOintFromJSON,
    ReplyVOintToJSON,
} from '../models';

export interface DelIndexUsingDELETERequest {
    indexNames?: Array<string>;
}

/**
 * 
 */
export class EsApi extends runtime.BaseAPI {

    /**
     * 删除索引
     */
    async delIndexUsingDELETERaw(requestParameters: DelIndexUsingDELETERequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReplyVOint>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["TOKEN"] = this.configuration.apiKey("TOKEN"); // Authorization authentication
        }

        const response = await this.request({
            path: `/api/databoard/board/es`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.indexNames,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReplyVOintFromJSON(jsonValue));
    }

    /**
     * 删除索引
     */
    async delIndexUsingDELETE(requestParameters: DelIndexUsingDELETERequest, initOverrides?: RequestInit): Promise<ReplyVOint> {
        const response = await this.delIndexUsingDELETERaw(requestParameters, initOverrides);
        return await response.value();
    }

}
