/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 新增【表字段信息】的参数
 * @export
 * @interface FieldDefAddDTO
 */
export interface FieldDefAddDTO {
    /**
     * 字段描述
     * @type {string}
     * @memberof FieldDefAddDTO
     */
    description?: string;
    /**
     * 字段Id
     * @type {string}
     * @memberof FieldDefAddDTO
     */
    fieldId: string;
    /**
     * 字段名称
     * @type {string}
     * @memberof FieldDefAddDTO
     */
    fieldName: string;
    /**
     * 关联
     * @type {string}
     * @memberof FieldDefAddDTO
     */
    tableId: string;
    /**
     * 字段类型：boolean,long,double,string,date
     * @type {string}
     * @memberof FieldDefAddDTO
     */
    type: string;
}

export function FieldDefAddDTOFromJSON(json: any): FieldDefAddDTO {
    return FieldDefAddDTOFromJSONTyped(json, false);
}

export function FieldDefAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldDefAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'fieldId': json['fieldId'],
        'fieldName': json['fieldName'],
        'tableId': json['tableId'],
        'type': json['type'],
    };
}

export function FieldDefAddDTOToJSON(value?: FieldDefAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'fieldId': value.fieldId,
        'fieldName': value.fieldName,
        'tableId': value.tableId,
        'type': value.type,
    };
}

