/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("EsApi", () => {
  let instance: api.EsApi
  beforeEach(function() {
    instance = new api.EsApi(config)
  });

  test("delIndexUsingDELETE", () => {
    const body: Array<string> = undefined
    return expect(instance.delIndexUsingDELETE(body, {})).resolves.toBe(null)
  })
})

