/**
 * 接口文档
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: 67890211@qq.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("CreditQueryControllerApi", () => {
  let instance: api.CreditQueryControllerApi
  beforeEach(function() {
    instance = new api.CreditQueryControllerApi(config)
  });

  test("getAllMsgForMapUsingPOST", () => {
    const accountTime: string = "accountTime_example"
    const type: string = "type_example"
    return expect(instance.getAllMsgForMapUsingPOST(accountTime, type, {})).resolves.toBe(null)
  })
  test("pastCreditCardBillGatherUsingPOST", () => {
    return expect(instance.pastCreditCardBillGatherUsingPOST({})).resolves.toBe(null)
  })
})

